import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import { Toaster } from 'sonner'
import Footer from '@/components/footer'
import { Header } from '@/components/header/index'

const roboto = Roboto({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const dynamic = 'force-static'
export const revalidate = false

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="next-disable-prefetch" content="true" />
        <meta name="robots" content="noindex, nofollow" />
      </head>
      <body
        className={`${roboto.className} antialiased min-h-screen flex flex-col`}
        cz-shortcut-listen="true"
      >
        <Header.Root />
        <div className="flex-1">{children}</div>
        <Footer />
        <Toaster />
      </body>
    </html>
  )
}
